spring.application.name=helpdesk-api-java

api.security.token.secret=${JWT_SECRET:my-secret-key}
api.security.token.access-expiration-seconds=${JWT_ACCESS_EXPIRATION_SECONDS:900}
api.security.token.refresh-expiration-seconds=${JWT_REFRESH_EXPIRATION_SECONDS:604800}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
