spring.datasource.url=jdbc:postgresql://localhost:5432/helpdesk
spring.datasource.username=paulo
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

api.security.token.secret=${JWT_SECRET:my-secret-key}
