spring.application.name=helpdesk-api-java

api.security.token.secret=${JWT_SECRET:my-secret-key}
spring.profiles.active=dev

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
