CREATE TABLE IF NOT EXISTS tb_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    status VARCHAR(32) NOT NULL,
    priority VARCHAR(32) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    closed_at TIMESTAMP(6) WITH TIME ZONE,
    client_id BIGINT NOT NULL,
    attendant_id BIGINT
);

CREATE TABLE IF NOT EXISTS tb_refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS tb_ticket_comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    content VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_ticket_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL,
    actor_id BIGINT NOT NULL,
    type VARCHAR(32) NOT NULL,
    previous_status VARCHAR(32),
    new_status VARCHAR(32),
    description VARCHAR(500) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

ALTER TABLE tb_user
    ALTER COLUMN name TYPE VARCHAR(100),
    ALTER COLUMN name SET NOT NULL,
    ALTER COLUMN email TYPE VARCHAR(255),
    ALTER COLUMN email SET NOT NULL,
    ALTER COLUMN password TYPE VARCHAR(255),
    ALTER COLUMN password SET NOT NULL,
    ALTER COLUMN role TYPE VARCHAR(32),
    ALTER COLUMN role SET NOT NULL;

ALTER TABLE tb_ticket
    ALTER COLUMN title TYPE VARCHAR(120),
    ALTER COLUMN title SET NOT NULL,
    ALTER COLUMN description TYPE VARCHAR(1000),
    ALTER COLUMN description SET NOT NULL,
    ALTER COLUMN status TYPE VARCHAR(32),
    ALTER COLUMN status SET NOT NULL,
    ALTER COLUMN priority TYPE VARCHAR(32),
    ALTER COLUMN priority SET NOT NULL,
    ALTER COLUMN created_at SET NOT NULL,
    ALTER COLUMN client_id SET NOT NULL;

ALTER TABLE tb_refresh_token
    ALTER COLUMN token_hash TYPE VARCHAR(64),
    ALTER COLUMN token_hash SET NOT NULL,
    ALTER COLUMN user_id SET NOT NULL,
    ALTER COLUMN expires_at SET NOT NULL,
    ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE tb_ticket_comment
    ALTER COLUMN ticket_id SET NOT NULL,
    ALTER COLUMN author_id SET NOT NULL,
    ALTER COLUMN content TYPE VARCHAR(2000),
    ALTER COLUMN content SET NOT NULL,
    ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE tb_ticket_history
    ALTER COLUMN ticket_id SET NOT NULL,
    ALTER COLUMN actor_id SET NOT NULL,
    ALTER COLUMN type TYPE VARCHAR(32),
    ALTER COLUMN type SET NOT NULL,
    ALTER COLUMN previous_status TYPE VARCHAR(32),
    ALTER COLUMN new_status TYPE VARCHAR(32),
    ALTER COLUMN description TYPE VARCHAR(500),
    ALTER COLUMN description SET NOT NULL,
    ALTER COLUMN created_at SET NOT NULL;

DO $$
DECLARE
    constraint_record RECORD;
BEGIN
    FOR constraint_record IN
        SELECT conrelid::regclass AS table_name, conname
        FROM pg_constraint
        WHERE contype IN ('f', 'c')
          AND conrelid IN (
              'tb_user'::regclass,
              'tb_ticket'::regclass,
              'tb_refresh_token'::regclass,
              'tb_ticket_comment'::regclass,
              'tb_ticket_history'::regclass
          )
    LOOP
        EXECUTE format(
            'ALTER TABLE %s DROP CONSTRAINT %I',
            constraint_record.table_name,
            constraint_record.conname
        );
    END LOOP;
END
$$;

ALTER TABLE tb_user
    ADD CONSTRAINT ck_user_role
        CHECK (role IN ('ROLE_USER', 'ROLE_ADMIN'));

ALTER TABLE tb_ticket
    ADD CONSTRAINT ck_ticket_status
        CHECK (status IN ('OPEN', 'IN_PROGRESS', 'WAITING_CLIENT', 'RESOLVED', 'CLOSED', 'CANCELED')),
    ADD CONSTRAINT ck_ticket_priority
        CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
    ADD CONSTRAINT fk_ticket_client
        FOREIGN KEY (client_id) REFERENCES tb_user (id),
    ADD CONSTRAINT fk_ticket_attendant
        FOREIGN KEY (attendant_id) REFERENCES tb_user (id);

ALTER TABLE tb_refresh_token
    ADD CONSTRAINT fk_refresh_token_user
        FOREIGN KEY (user_id) REFERENCES tb_user (id) ON DELETE CASCADE;

ALTER TABLE tb_ticket_comment
    ADD CONSTRAINT fk_ticket_comment_ticket
        FOREIGN KEY (ticket_id) REFERENCES tb_ticket (id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_ticket_comment_author
        FOREIGN KEY (author_id) REFERENCES tb_user (id);

ALTER TABLE tb_ticket_history
    ADD CONSTRAINT ck_ticket_history_type
        CHECK (type IN ('CREATED', 'ASSIGNED', 'STATUS_CHANGED', 'REOPENED', 'COMMENT_ADDED')),
    ADD CONSTRAINT ck_ticket_history_previous_status
        CHECK (previous_status IS NULL OR previous_status IN ('OPEN', 'IN_PROGRESS', 'WAITING_CLIENT', 'RESOLVED', 'CLOSED', 'CANCELED')),
    ADD CONSTRAINT ck_ticket_history_new_status
        CHECK (new_status IS NULL OR new_status IN ('OPEN', 'IN_PROGRESS', 'WAITING_CLIENT', 'RESOLVED', 'CLOSED', 'CANCELED')),
    ADD CONSTRAINT fk_ticket_history_ticket
        FOREIGN KEY (ticket_id) REFERENCES tb_ticket (id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_ticket_history_actor
        FOREIGN KEY (actor_id) REFERENCES tb_user (id);

DROP INDEX IF EXISTS uk_user_email;
DROP INDEX IF EXISTS uk_refresh_token_hash;

CREATE UNIQUE INDEX uk_user_email ON tb_user (LOWER(email));
CREATE UNIQUE INDEX uk_refresh_token_hash ON tb_refresh_token (token_hash);

CREATE INDEX IF NOT EXISTS idx_ticket_status ON tb_ticket (status);
CREATE INDEX IF NOT EXISTS idx_ticket_priority ON tb_ticket (priority);
CREATE INDEX IF NOT EXISTS idx_ticket_client ON tb_ticket (client_id);
CREATE INDEX IF NOT EXISTS idx_ticket_attendant ON tb_ticket (attendant_id);
CREATE INDEX IF NOT EXISTS idx_ticket_created_at ON tb_ticket (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ticket_comment_ticket_created
    ON tb_ticket_comment (ticket_id, created_at);
CREATE INDEX IF NOT EXISTS idx_ticket_history_ticket_created
    ON tb_ticket_history (ticket_id, created_at);
CREATE INDEX IF NOT EXISTS idx_refresh_token_user ON tb_refresh_token (user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_token_expires_at ON tb_refresh_token (expires_at);
